name: default-environment
channels:
  - conda-forge
dependencies:
  - python==3.7.3
  - numpy==1.16.4
  - pip==19.2.1
  - nb_conda==2.2.1
  - nb_conda_kernels==2.2.2
  - sympy==1.4
  - sphinx-gallery==0.4.0
  - pandas==0.25.0
  - matplotlib==3.1.1
  - bokeh==1.3.1
  - ipywidgets==7.5.1
  - scipy==1.3.0
  - astropy==3.2.1
  - bqplot==0.11.6
  - pip:
    - nbgitpuller==0.7.0

